 services:
  postgres:
    image: postgres:17.0-alpine
    container_name: postgres
    env_file: ".env"
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - ${POSTGRES_DB_HOST_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
      interval: 3s
      timeout: 3s
      start_period: 5s
      retries: 5
    restart: always

volumes:
  pgdata:
