name: recall

networks:
  dev:

services:
  backend-app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - dev
  minio-setup:
    container_name: minio-setup
    depends_on:
      minio:
        condition: service_healthy
    image: minio/mc:latest
    env_file:
      - ./config/minio-server.env
      - ./config/minio-backend.env
    environment:
      - "MINIO_SERVER_HOSTNAME=http://minio:9000"
    volumes:
      - recall-minio-volume:/mnt/minio-volume
      - ./config/minio-setup.sh:/setup.sh
    entrypoint: bash /setup.sh
    restart: always
    networks:
      - dev
  minio:
    container_name: minio
    image: minio/minio:latest
    environment:
      - MINIO_CONFIG_ENV_FILE=/etc/config.env
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_BROWSER_PORT}:9001"
    volumes:
      - recall-minio-volume:/mnt/minio-volume
      - ./config/minio-server.env:/etc/config.env
    command: server --console-address ":9001"
    healthcheck:
      test: "curl -f http://localhost:9000/minio/health/live"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always
    networks:
      - dev
  postgres:
    image: postgres:17.0-alpine
    container_name: postgres
    env_file: ./config/postgres.env
    ports:
      - ${POSTGRES_HOST_PORT}:5432
    volumes:
      - recall-pgdata-volume:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U backend -d recall_db"
      interval: 3s
      timeout: 3s
      start_period: 5s
      retries: 5
    restart: always
    networks:
      - dev

volumes:
  recall-minio-volume:
    driver_opts:
      type: none
      o: bind
      device: $MINIO_VOLUME_PATH
  recall-pgdata-volume:
    driver_opts:
      type: none
      o: bind
      device: $POSTGRES_VOLUME_PATH
