[pytest]
testpaths = tests
pythonpath = .
env = 
    SECRET_KEY=test_secret_key
    ACCESS_TOKEN_KEY=test_access_token
    POSTGRES_USER=test_user
    POSTGRES_PASSWORD=test_password
    POSTGRES_HOST=localhost
    POSTGRES_HOST_PORT=5432
    POSTGRES_DB=test_db
    MINIO_BUCKET_NAME=test_bucket
    MINIO_HOSTNAME=localhost
    MINIO_PORT=9000
    MINIO_LOGIN=test_minio_user
    MINIO_PASSWORD=test_minio_password
    MINIO_MAX_FILE_MB_SIZE=10
    OLLAMA_MODEL=test_model
    OLLAMA_HOSTNAME=localhost
    OLLAMA_PORT=11434