services:
  minio-setup:
    container_name: minio-setup
    depends_on:
      minio:
        condition: service_healthy
        restart: true
    image: minio/mc:latest
    env_file: ./minio_config/.env
    environment:
      - "MINIO_SERVER_HOSTNAME=http://minio:9000"
    volumes:
      - /mnt/minio-volume:/mnt/minio-volume
      - ./minio_config/setup.sh:/setup.sh
    entrypoint: bash /setup.sh
  minio:
    container_name: minio
    image: minio/minio:latest
    environment:
      - MINIO_CONFIG_ENV_FILE=/etc/config.env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /mnt/minio-volume:/mnt/minio-volume
      - ./minio_config/minio.conf:/etc/config.env
    command: server --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
      start_interval: 5s
